CREATE DATABASE IF NOT EXISTS ms_authentication;

CREATE TABLE colaboradores(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NULL,
    email VARCHAR(255) UNIQUE NULL,
    funcao VARCHAR(255) NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);