CREATE TABLE organizacoes(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome_empresarial VARCHAR(255) NULL,
    cnpj VARCHAR(255) UNIQUE NULL,
    senha VARCHAR(255) NULL,
    organizacao_id INT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);